MODEL:
  NAME: 'resnet50'
  TYPE: 'backbone'
  NUM_CLASSES: 1000
  WEIGHTS: 'tmp/checkpoints/R192_MACs_3.0B_acc_74.38.ckpt'
TEST:
  BATCH_SIZE: 400
SCALING:
  RES_MULT_A: 0.86
  WIDTH_MULT: 1.0
DATASET:
#  PATH: "/home/hao/Downloads/"
  NAME: 'imagenet'
NUM_GPUS: 4
