MODEL:
  NAME: 'resnet50'
  TYPE: 'backbone'
  NUM_CLASSES: 1000
  LOAD_WEIGHTS_FROM_URL: False
  BOX_WEIGHTS: 'tmp/checkpoints/foreground_predictor.ckpt'
  WEIGHTS: 'tmp/checkpoints/SSR192_MACs_3.1B_acc_76.28.ckpt'
TEST:
  BATCH_SIZE: 400
CROP:
  TYPE: 'cropnet_anynet_light_box'
  SHAPE: 'square'
  TUNE_STRIDE: 100
  TUNE_PROB: 0.7
  REGULATE: True
SCALING:
  RES_MULT_B: 0.86
  WIDTH_MULT: 1.0
DATASET:
  NAME: 'imagenet_for_crop'
NUM_GPUS: 4
